run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - goheader
    - goimports
    - gofmt
    - govet
    - gosec
    - gosimple
    - misspell
    - ineffassign
    - typecheck
#    - unused
    - whitespace
    - gocyclo
    - nakedret
    - revive

linters-settings:
  goheader:
    template-path: .go-header.txt
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: unused-parameter
        disabled: true

issues:
  exclude-dirs-use-default: false
  exclude-dirs:
    - hack/bin
    - testdata$
    - examples$
    - internal/static
  exclude-files:
  - "zz_*"
  - ".*test.go"
  exclude-rules:
    - linters:
        - goheader
      text: "ysicing"
    - linters:
        - gosec
      text: "G115"
