run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - goheader
    - goimports
    - gofmt
    - govet
    - gosec
    - gosimple
    - misspell
    - ineffassign
    - typecheck
    - unused
    - whitespace
    - gocyclo
    - nakedret
    - revive

linters-settings:
  goheader:
    template-path: .go-header.txt
  revive:
    ignore-generated: true
    ignore-generated-header: true
    severity: warning
    rules:
      - name: unused-parameter
        disabled: true
