server:
    install_lock: true
    app_name: Tiga Dashboard
    domain: localhost
    http_port: 12306
    grpc_domain: localhost
    grpc_port: 12307
    language: zh-CN
database:
    type: sqlite
    database: /tmp/tidb.v9.db
security:
    jwt_secret: 6dJnIOS7Av7fJd2qlXitcjyWWZ4Al3h2uM9b-FGQ_u0=
    encryption_key: u7K3H4g1O0iuPW0Cns-ue2mHbcU3Aql-2fi-Ro7Ivno=
