server:
    install_lock: true
    app_name: Tiga Dashboard
    domain: localhost
    http_port: 12306
    grpc_domain: localhost
    grpc_port: 12307
    language: zh-CN
database:
    type: sqlite
    database: /tmp/tiga2025.sql
security:
    jwt_secret: MWVppPgsuBNZcOxcavYaa81v9cDrgc0ygo2quU9y7wM=
    encryption_key: wQ0b1sLu6XwlhzQKg91QWJzxI22Qb6XAt2kh4ATRalg=
