generated: "2021-10-20T14:00:00Z"
repositories:
- name: "helm"
  home: "helm.sh"
  desc: "helm"
  version: 0.0.1
  type: tgz
  platforms:
    - os: linux
      arch: arm64
      url: ""
    - os: linux
      arch: amd64
      url: ""
