// Code generated by spec-kit:implement; DO NOT EDIT.
// This file was generated at 2025-10-29 22:15:00
// Source: .claude/specs/010-k8s-pod-009/tasks.md (task: T035)

import React, { useState } from 'react';
import { K8sRecordingList } from '../../components/k8s/K8sRecordingList';
import { K8sAuditLogList } from '../../components/k8s/K8sAuditLogList';

export const K8sAuditPage: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'recordings' | 'audit'>('recordings');

  return (
    <div className="min-h-screen bg-gray-50">
      {/* 页面头部 */}
      <div className="bg-white shadow">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="py-6">
            <h1 className="text-3xl font-bold text-gray-900">K8s 审计与录制</h1>
            <p className="mt-2 text-sm text-gray-600">
              查看 K8s 集群操作审计日志和终端录制记录
            </p>
          </div>
        </div>
      </div>

      {/* 选项卡导航 */}
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <nav className="-mb-px flex space-x-8">
            <button
              onClick={() => setActiveTab('recordings')}
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === 'recordings'
                  ? 'border-blue-500 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              终端录制
            </button>
            <button
              onClick={() => setActiveTab('audit')}
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === 'audit'
                  ? 'border-blue-500 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              审计日志
            </button>
          </nav>
        </div>
      </div>

      {/* 内容区域 */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {activeTab === 'recordings' && <K8sRecordingList />}
        {activeTab === 'audit' && <K8sAuditLogList />}
      </div>
    </div>
  );
};
