// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/host_monitor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HostMonitorClient is the client API for HostMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostMonitorClient interface {
	// ReportState Agent上报监控数据(双向流)
	ReportState(ctx context.Context, opts ...grpc.CallOption) (HostMonitor_ReportStateClient, error)
	// RegisterAgent Agent注册
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	// ReportProbeResultBatch Agent批量上报探测结果
	ReportProbeResultBatch(ctx context.Context, in *ReportProbeResultBatchRequest, opts ...grpc.CallOption) (*ReportProbeResultBatchResponse, error)
	// Heartbeat 心跳保持
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// IOStream PTY终端I/O流(双向流)
	IOStream(ctx context.Context, opts ...grpc.CallOption) (HostMonitor_IOStreamClient, error)
}

type hostMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewHostMonitorClient(cc grpc.ClientConnInterface) HostMonitorClient {
	return &hostMonitorClient{cc}
}

func (c *hostMonitorClient) ReportState(ctx context.Context, opts ...grpc.CallOption) (HostMonitor_ReportStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &HostMonitor_ServiceDesc.Streams[0], "/proto.HostMonitor/ReportState", opts...)
	if err != nil {
		return nil, err
	}
	x := &hostMonitorReportStateClient{stream}
	return x, nil
}

type HostMonitor_ReportStateClient interface {
	Send(*ReportStateRequest) error
	Recv() (*ReportStateResponse, error)
	grpc.ClientStream
}

type hostMonitorReportStateClient struct {
	grpc.ClientStream
}

func (x *hostMonitorReportStateClient) Send(m *ReportStateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hostMonitorReportStateClient) Recv() (*ReportStateResponse, error) {
	m := new(ReportStateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hostMonitorClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, "/proto.HostMonitor/RegisterAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostMonitorClient) ReportProbeResultBatch(ctx context.Context, in *ReportProbeResultBatchRequest, opts ...grpc.CallOption) (*ReportProbeResultBatchResponse, error) {
	out := new(ReportProbeResultBatchResponse)
	err := c.cc.Invoke(ctx, "/proto.HostMonitor/ReportProbeResultBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostMonitorClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/proto.HostMonitor/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostMonitorClient) IOStream(ctx context.Context, opts ...grpc.CallOption) (HostMonitor_IOStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &HostMonitor_ServiceDesc.Streams[1], "/proto.HostMonitor/IOStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &hostMonitorIOStreamClient{stream}
	return x, nil
}

type HostMonitor_IOStreamClient interface {
	Send(*IOStreamData) error
	Recv() (*IOStreamData, error)
	grpc.ClientStream
}

type hostMonitorIOStreamClient struct {
	grpc.ClientStream
}

func (x *hostMonitorIOStreamClient) Send(m *IOStreamData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hostMonitorIOStreamClient) Recv() (*IOStreamData, error) {
	m := new(IOStreamData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HostMonitorServer is the server API for HostMonitor service.
// All implementations must embed UnimplementedHostMonitorServer
// for forward compatibility
type HostMonitorServer interface {
	// ReportState Agent上报监控数据(双向流)
	ReportState(HostMonitor_ReportStateServer) error
	// RegisterAgent Agent注册
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	// ReportProbeResultBatch Agent批量上报探测结果
	ReportProbeResultBatch(context.Context, *ReportProbeResultBatchRequest) (*ReportProbeResultBatchResponse, error)
	// Heartbeat 心跳保持
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// IOStream PTY终端I/O流(双向流)
	IOStream(HostMonitor_IOStreamServer) error
	mustEmbedUnimplementedHostMonitorServer()
}

// UnimplementedHostMonitorServer must be embedded to have forward compatible implementations.
type UnimplementedHostMonitorServer struct {
}

func (UnimplementedHostMonitorServer) ReportState(HostMonitor_ReportStateServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportState not implemented")
}
func (UnimplementedHostMonitorServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedHostMonitorServer) ReportProbeResultBatch(context.Context, *ReportProbeResultBatchRequest) (*ReportProbeResultBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportProbeResultBatch not implemented")
}
func (UnimplementedHostMonitorServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedHostMonitorServer) IOStream(HostMonitor_IOStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method IOStream not implemented")
}
func (UnimplementedHostMonitorServer) mustEmbedUnimplementedHostMonitorServer() {}

// UnsafeHostMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostMonitorServer will
// result in compilation errors.
type UnsafeHostMonitorServer interface {
	mustEmbedUnimplementedHostMonitorServer()
}

func RegisterHostMonitorServer(s grpc.ServiceRegistrar, srv HostMonitorServer) {
	s.RegisterService(&HostMonitor_ServiceDesc, srv)
}

func _HostMonitor_ReportState_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HostMonitorServer).ReportState(&hostMonitorReportStateServer{stream})
}

type HostMonitor_ReportStateServer interface {
	Send(*ReportStateResponse) error
	Recv() (*ReportStateRequest, error)
	grpc.ServerStream
}

type hostMonitorReportStateServer struct {
	grpc.ServerStream
}

func (x *hostMonitorReportStateServer) Send(m *ReportStateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hostMonitorReportStateServer) Recv() (*ReportStateRequest, error) {
	m := new(ReportStateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HostMonitor_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostMonitorServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HostMonitor/RegisterAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostMonitorServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostMonitor_ReportProbeResultBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportProbeResultBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostMonitorServer).ReportProbeResultBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HostMonitor/ReportProbeResultBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostMonitorServer).ReportProbeResultBatch(ctx, req.(*ReportProbeResultBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostMonitor_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostMonitorServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HostMonitor/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostMonitorServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostMonitor_IOStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HostMonitorServer).IOStream(&hostMonitorIOStreamServer{stream})
}

type HostMonitor_IOStreamServer interface {
	Send(*IOStreamData) error
	Recv() (*IOStreamData, error)
	grpc.ServerStream
}

type hostMonitorIOStreamServer struct {
	grpc.ServerStream
}

func (x *hostMonitorIOStreamServer) Send(m *IOStreamData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hostMonitorIOStreamServer) Recv() (*IOStreamData, error) {
	m := new(IOStreamData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HostMonitor_ServiceDesc is the grpc.ServiceDesc for HostMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HostMonitor",
	HandlerType: (*HostMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _HostMonitor_RegisterAgent_Handler,
		},
		{
			MethodName: "ReportProbeResultBatch",
			Handler:    _HostMonitor_ReportProbeResultBatch_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _HostMonitor_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportState",
			Handler:       _HostMonitor_ReportState_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "IOStream",
			Handler:       _HostMonitor_IOStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/host_monitor.proto",
}
