// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/service_probe.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceProbe_ExecuteProbe_FullMethodName = "/proto.ServiceProbe/ExecuteProbe"
)

// ServiceProbeClient is the client API for ServiceProbe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ServiceProbe 服务探测服务
type ServiceProbeClient interface {
	// ExecuteProbe 执行探测任务(双向流)
	ExecuteProbe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProbeTaskRequest, ProbeResultResponse], error)
}

type serviceProbeClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceProbeClient(cc grpc.ClientConnInterface) ServiceProbeClient {
	return &serviceProbeClient{cc}
}

func (c *serviceProbeClient) ExecuteProbe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProbeTaskRequest, ProbeResultResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServiceProbe_ServiceDesc.Streams[0], ServiceProbe_ExecuteProbe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProbeTaskRequest, ProbeResultResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceProbe_ExecuteProbeClient = grpc.BidiStreamingClient[ProbeTaskRequest, ProbeResultResponse]

// ServiceProbeServer is the server API for ServiceProbe service.
// All implementations must embed UnimplementedServiceProbeServer
// for forward compatibility.
//
// ServiceProbe 服务探测服务
type ServiceProbeServer interface {
	// ExecuteProbe 执行探测任务(双向流)
	ExecuteProbe(grpc.BidiStreamingServer[ProbeTaskRequest, ProbeResultResponse]) error
	mustEmbedUnimplementedServiceProbeServer()
}

// UnimplementedServiceProbeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceProbeServer struct{}

func (UnimplementedServiceProbeServer) ExecuteProbe(grpc.BidiStreamingServer[ProbeTaskRequest, ProbeResultResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteProbe not implemented")
}
func (UnimplementedServiceProbeServer) mustEmbedUnimplementedServiceProbeServer() {}
func (UnimplementedServiceProbeServer) testEmbeddedByValue()                      {}

// UnsafeServiceProbeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceProbeServer will
// result in compilation errors.
type UnsafeServiceProbeServer interface {
	mustEmbedUnimplementedServiceProbeServer()
}

func RegisterServiceProbeServer(s grpc.ServiceRegistrar, srv ServiceProbeServer) {
	// If the following call pancis, it indicates UnimplementedServiceProbeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceProbe_ServiceDesc, srv)
}

func _ServiceProbe_ExecuteProbe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceProbeServer).ExecuteProbe(&grpc.GenericServerStream[ProbeTaskRequest, ProbeResultResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceProbe_ExecuteProbeServer = grpc.BidiStreamingServer[ProbeTaskRequest, ProbeResultResponse]

// ServiceProbe_ServiceDesc is the grpc.ServiceDesc for ServiceProbe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceProbe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ServiceProbe",
	HandlerType: (*ServiceProbeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteProbe",
			Handler:       _ServiceProbe_ExecuteProbe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/service_probe.proto",
}
