// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/terminal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建会话请求
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                            // 主机UUID
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Cols          int32                  `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`                           // 终端列数
	Rows          int32                  `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`                           // 终端行数
	SshUser       string                 `protobuf:"bytes,5,opt,name=ssh_user,json=sshUser,proto3" json:"ssh_user,omitempty"`       // SSH用户名
	SshPort       int32                  `protobuf:"varint,6,opt,name=ssh_port,json=sshPort,proto3" json:"ssh_port,omitempty"`      // SSH端口
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_terminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_terminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CreateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CreateSessionRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *CreateSessionRequest) GetSshUser() string {
	if x != nil {
		return x.SshUser
	}
	return ""
}

func (x *CreateSessionRequest) GetSshPort() int32 {
	if x != nil {
		return x.SshPort
	}
	return 0
}

// 创建会话响应
type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                     // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 消息
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_terminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_terminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_terminal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 终端请求(Server → Agent)
type TerminalRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	// Types that are valid to be assigned to Payload:
	//
	//	*TerminalRequest_Input
	//	*TerminalRequest_Resize
	//	*TerminalRequest_Close
	Payload       isTerminalRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalRequest) Reset() {
	*x = TerminalRequest{}
	mi := &file_proto_terminal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalRequest) ProtoMessage() {}

func (x *TerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_terminal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalRequest.ProtoReflect.Descriptor instead.
func (*TerminalRequest) Descriptor() ([]byte, []int) {
	return file_proto_terminal_proto_rawDescGZIP(), []int{2}
}

func (x *TerminalRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalRequest) GetPayload() isTerminalRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TerminalRequest) GetInput() *TerminalInput {
	if x != nil {
		if x, ok := x.Payload.(*TerminalRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *TerminalRequest) GetResize() *ResizeRequest {
	if x != nil {
		if x, ok := x.Payload.(*TerminalRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *TerminalRequest) GetClose() *CloseRequest {
	if x != nil {
		if x, ok := x.Payload.(*TerminalRequest_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isTerminalRequest_Payload interface {
	isTerminalRequest_Payload()
}

type TerminalRequest_Input struct {
	Input *TerminalInput `protobuf:"bytes,2,opt,name=input,proto3,oneof"` // 终端输入
}

type TerminalRequest_Resize struct {
	Resize *ResizeRequest `protobuf:"bytes,3,opt,name=resize,proto3,oneof"` // 调整大小
}

type TerminalRequest_Close struct {
	Close *CloseRequest `protobuf:"bytes,4,opt,name=close,proto3,oneof"` // 关闭会话
}

func (*TerminalRequest_Input) isTerminalRequest_Payload() {}

func (*TerminalRequest_Resize) isTerminalRequest_Payload() {}

func (*TerminalRequest_Close) isTerminalRequest_Payload() {}

// 终端响应(Agent → Server)
type TerminalResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	// Types that are valid to be assigned to Payload:
	//
	//	*TerminalResponse_Output
	//	*TerminalResponse_Error
	Payload       isTerminalResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResponse) Reset() {
	*x = TerminalResponse{}
	mi := &file_proto_terminal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResponse) ProtoMessage() {}

func (x *TerminalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_terminal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResponse.ProtoReflect.Descriptor instead.
func (*TerminalResponse) Descriptor() ([]byte, []int) {
	return file_proto_terminal_proto_rawDescGZIP(), []int{3}
}

func (x *TerminalResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalResponse) GetPayload() isTerminalResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TerminalResponse) GetOutput() *TerminalOutput {
	if x != nil {
		if x, ok := x.Payload.(*TerminalResponse_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *TerminalResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*TerminalResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTerminalResponse_Payload interface {
	isTerminalResponse_Payload()
}

type TerminalResponse_Output struct {
	Output *TerminalOutput `protobuf:"bytes,2,opt,name=output,proto3,oneof"` // 终端输出
}

type TerminalResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // 错误消息
}

func (*TerminalResponse_Output) isTerminalResponse_Payload() {}

func (*TerminalResponse_Error) isTerminalResponse_Payload() {}

// 终端输入
type TerminalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 输入数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_proto_terminal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_terminal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_proto_terminal_proto_rawDescGZIP(), []int{4}
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 终端输出
type TerminalOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 输出数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOutput) Reset() {
	*x = TerminalOutput{}
	mi := &file_proto_terminal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOutput) ProtoMessage() {}

func (x *TerminalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_terminal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOutput.ProtoReflect.Descriptor instead.
func (*TerminalOutput) Descriptor() ([]byte, []int) {
	return file_proto_terminal_proto_rawDescGZIP(), []int{5}
}

func (x *TerminalOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 调整大小请求
type ResizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          int32                  `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"` // 新列数
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"` // 新行数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	mi := &file_proto_terminal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_terminal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_terminal_proto_rawDescGZIP(), []int{6}
}

func (x *ResizeRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ResizeRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// 关闭请求
type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // 关闭原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_proto_terminal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_terminal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_terminal_proto_rawDescGZIP(), []int{7}
}

func (x *CloseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 错误响应
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 错误消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_terminal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_terminal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_terminal_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 关闭会话请求
type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_proto_terminal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_terminal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_terminal_proto_rawDescGZIP(), []int{9}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 关闭会话响应
type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_proto_terminal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_terminal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_terminal_proto_rawDescGZIP(), []int{10}
}

func (x *CloseSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_terminal_proto protoreflect.FileDescriptor

const file_proto_terminal_proto_rawDesc = "" +
	"\n" +
	"\x14proto/terminal.proto\x12\x05proto\"\xa7\x01\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x05R\x04rows\x12\x19\n" +
	"\bssh_user\x18\x05 \x01(\tR\asshUser\x12\x19\n" +
	"\bssh_port\x18\x06 \x01(\x05R\asshPort\"j\n" +
	"\x15CreateSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xc6\x01\n" +
	"\x0fTerminalRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\x05input\x18\x02 \x01(\v2\x14.proto.TerminalInputH\x00R\x05input\x12.\n" +
	"\x06resize\x18\x03 \x01(\v2\x14.proto.ResizeRequestH\x00R\x06resize\x12+\n" +
	"\x05close\x18\x04 \x01(\v2\x13.proto.CloseRequestH\x00R\x05closeB\t\n" +
	"\apayload\"\x9b\x01\n" +
	"\x10TerminalResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12/\n" +
	"\x06output\x18\x02 \x01(\v2\x15.proto.TerminalOutputH\x00R\x06output\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x14.proto.ErrorResponseH\x00R\x05errorB\t\n" +
	"\apayload\"#\n" +
	"\rTerminalInput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"$\n" +
	"\x0eTerminalOutput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"7\n" +
	"\rResizeRequest\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\"&\n" +
	"\fCloseRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\")\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"J\n" +
	"\x14CloseSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe0\x01\n" +
	"\bTerminal\x12J\n" +
	"\rCreateSession\x12\x1b.proto.CreateSessionRequest\x1a\x1c.proto.CreateSessionResponse\x12?\n" +
	"\bTerminal\x12\x16.proto.TerminalRequest\x1a\x17.proto.TerminalResponse(\x010\x01\x12G\n" +
	"\fCloseSession\x12\x1a.proto.CloseSessionRequest\x1a\x1b.proto.CloseSessionResponseB%Z#github.com/ysicing/tiga/proto;protob\x06proto3"

var (
	file_proto_terminal_proto_rawDescOnce sync.Once
	file_proto_terminal_proto_rawDescData []byte
)

func file_proto_terminal_proto_rawDescGZIP() []byte {
	file_proto_terminal_proto_rawDescOnce.Do(func() {
		file_proto_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_terminal_proto_rawDesc), len(file_proto_terminal_proto_rawDesc)))
	})
	return file_proto_terminal_proto_rawDescData
}

var file_proto_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_terminal_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),  // 0: proto.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 1: proto.CreateSessionResponse
	(*TerminalRequest)(nil),       // 2: proto.TerminalRequest
	(*TerminalResponse)(nil),      // 3: proto.TerminalResponse
	(*TerminalInput)(nil),         // 4: proto.TerminalInput
	(*TerminalOutput)(nil),        // 5: proto.TerminalOutput
	(*ResizeRequest)(nil),         // 6: proto.ResizeRequest
	(*CloseRequest)(nil),          // 7: proto.CloseRequest
	(*ErrorResponse)(nil),         // 8: proto.ErrorResponse
	(*CloseSessionRequest)(nil),   // 9: proto.CloseSessionRequest
	(*CloseSessionResponse)(nil),  // 10: proto.CloseSessionResponse
}
var file_proto_terminal_proto_depIdxs = []int32{
	4,  // 0: proto.TerminalRequest.input:type_name -> proto.TerminalInput
	6,  // 1: proto.TerminalRequest.resize:type_name -> proto.ResizeRequest
	7,  // 2: proto.TerminalRequest.close:type_name -> proto.CloseRequest
	5,  // 3: proto.TerminalResponse.output:type_name -> proto.TerminalOutput
	8,  // 4: proto.TerminalResponse.error:type_name -> proto.ErrorResponse
	0,  // 5: proto.Terminal.CreateSession:input_type -> proto.CreateSessionRequest
	2,  // 6: proto.Terminal.Terminal:input_type -> proto.TerminalRequest
	9,  // 7: proto.Terminal.CloseSession:input_type -> proto.CloseSessionRequest
	1,  // 8: proto.Terminal.CreateSession:output_type -> proto.CreateSessionResponse
	3,  // 9: proto.Terminal.Terminal:output_type -> proto.TerminalResponse
	10, // 10: proto.Terminal.CloseSession:output_type -> proto.CloseSessionResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_terminal_proto_init() }
func file_proto_terminal_proto_init() {
	if File_proto_terminal_proto != nil {
		return
	}
	file_proto_terminal_proto_msgTypes[2].OneofWrappers = []any{
		(*TerminalRequest_Input)(nil),
		(*TerminalRequest_Resize)(nil),
		(*TerminalRequest_Close)(nil),
	}
	file_proto_terminal_proto_msgTypes[3].OneofWrappers = []any{
		(*TerminalResponse_Output)(nil),
		(*TerminalResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_terminal_proto_rawDesc), len(file_proto_terminal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_terminal_proto_goTypes,
		DependencyIndexes: file_proto_terminal_proto_depIdxs,
		MessageInfos:      file_proto_terminal_proto_msgTypes,
	}.Build()
	File_proto_terminal_proto = out.File
	file_proto_terminal_proto_goTypes = nil
	file_proto_terminal_proto_depIdxs = nil
}
