// Code generated by spec-kit:implement; DO NOT EDIT.
// This file was generated at 2025-10-29 22:15:00
// Source: .claude/specs/010-k8s-pod-009/tasks.md (task: T034)

import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { useParams, useNavigate } from 'react-router-dom';
import { format } from 'date-fns';
import { zhCN } from 'date-fns/locale';

interface K8sAuditEvent {
  id: string;
  timestamp: number;
  action: string;
  resource_type: string;
  subsystem: string;
  user_id: string;
  username: string;
  client_ip: string;
  cluster_id?: string;
  namespace?: string;
  resource_name?: string;
  details?: any;
}

export const K8sAuditLogDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const { data, isLoading, error } = useQuery({
    queryKey: ['k8s-audit-event', id],
    queryFn: async () => {
      if (!id) throw new Error('Event ID is required');
      const response = await fetch(`/api/v1/audit/k8s/${id}`);
      if (!response.ok) {
        throw new Error('Failed to fetch audit event');
      }
      return response.json();
    },
    enabled: !!id,
  });

  if (isLoading) {
    return <div className="p-4">加载中...</div>;
  }

  if (error || !data) {
    return <div className="p-4 text-red-500">审计事件不存在</div>;
  }

  const event: K8sAuditEvent = data;

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="mb-6">
        <button
          onClick={() => navigate('/audit')}
          className="text-blue-600 hover:text-blue-800"
        >
          ← 返回列表
        </button>
      </div>

      <div className="bg-white rounded-lg shadow overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200">
          <h1 className="text-2xl font-bold">K8s 审计事件详情</h1>
        </div>

        <div className="p-6">
          <dl className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <dt className="text-sm font-medium text-gray-500">事件 ID</dt>
              <dd className="mt-1 text-sm text-gray-900">{event.id}</dd>
            </div>

            <div>
              <dt className="text-sm font-medium text-gray-500">时间戳</dt>
              <dd className="mt-1 text-sm text-gray-900">
                {format(new Date(event.timestamp), 'yyyy-MM-dd HH:mm:ss', { locale: zhCN })}
              </dd>
            </div>

            <div>
              <dt className="text-sm font-medium text-gray-500">操作</dt>
              <dd className="mt-1">
                <span className="px-2 py-1 text-xs font-semibold rounded bg-blue-100 text-blue-800">
                  {event.action}
                </span>
              </dd>
            </div>

            <div>
              <dt className="text-sm font-medium text-gray-500">资源类型</dt>
              <dd className="mt-1 text-sm text-gray-900">{event.resource_type}</dd>
            </div>

            <div>
              <dt className="text-sm font-medium text-gray-500">子系统</dt>
              <dd className="mt-1 text-sm text-gray-900">{event.subsystem}</dd>
            </div>

            <div>
              <dt className="text-sm font-medium text-gray-500">用户</dt>
              <dd className="mt-1 text-sm text-gray-900">
                {event.username || event.user_id}
              </dd>
            </div>

            <div>
              <dt className="text-sm font-medium text-gray-500">客户端 IP</dt>
              <dd className="mt-1 text-sm text-gray-900">{event.client_ip}</dd>
            </div>

            <div>
              <dt className="text-sm font-medium text-gray-500">集群 ID</dt>
              <dd className="mt-1 text-sm text-gray-900">{event.cluster_id || '-'}</dd>
            </div>

            <div>
              <dt className="text-sm font-medium text-gray-500">命名空间</dt>
              <dd className="mt-1 text-sm text-gray-900">{event.namespace || '-'}</dd>
            </div>

            <div>
              <dt className="text-sm font-medium text-gray-500">资源名称</dt>
              <dd className="mt-1 text-sm text-gray-900">{event.resource_name || '-'}</dd>
            </div>
          </dl>

          {/* 详细信息 */}
          {event.details && (
            <div className="mt-6">
              <dt className="text-sm font-medium text-gray-500 mb-2">详细信息</dt>
              <dd className="mt-1">
                <pre className="bg-gray-50 p-4 rounded-lg overflow-x-auto text-sm">
                  {JSON.stringify(event.details, null, 2)}
                </pre>
              </dd>
            </div>
          )}

          {/* 关联操作 */}
          <div className="mt-6 flex space-x-4">
            {event.resource_type === 'k8s_node' && event.details?.node_name && (
              <button
                onClick={() => window.open(`/cluster/${event.cluster_id}/node-terminal/${event.details.node_name}`, '_blank')}
                className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
              >
                打开节点终端
              </button>
            )}
            {event.resource_type === 'k8s_pod' && event.details?.pod_name && (
              <button
                onClick={() => window.open(`/cluster/${event.cluster_id}/terminal/${event.namespace}/${event.details.pod_name}?container=${event.details.container_name}`, '_blank')}
                className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
              >
                打开 Pod 终端
              </button>
            )}
            {event.details?.recording_id && (
              <button
                onClick={() => window.open(`/recordings/${event.details.recording_id}`, '_blank')}
                className="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600"
              >
                查看录制
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
