// Code generated by spec-kit:implement; DO NOT EDIT.
// This file was generated at 2025-10-29 22:15:00
// Source: .claude/specs/010-k8s-pod-009/tasks.md (task: T032)

import React, { useEffect, useRef } from 'react';

interface K8sRecordingPlayerProps {
  recordingId: string;
  autoPlay?: boolean;
}

export const K8sRecordingPlayer: React.FC<K8sRecordingPlayerProps> = ({
  recordingId,
  autoPlay = true
}) => {
  const playerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Load asciinema player
    const script = document.createElement('script');
    script.src = 'https://asciinema.org/asciinema-player.js';
    script.onload = () => {
      if (playerRef.current && (window as any).AsciinemaPlayer) {
        (window as any).AsciinemaPlayer.create(
          `/api/v1/recordings/${recordingId}/play`,
          playerRef.current,
          {
            autoPlay,
            loop: false,
            preload: true,
            rows: 24,
            cols: 80,
            speed: 1.0,
            theme: 'asciinema',
            title: 'K8s Terminal Recording',
          }
        );
      }
    };
    document.body.appendChild(script);

    return () => {
      if (document.body.contains(script)) {
        document.body.removeChild(script);
      }
    };
  }, [recordingId, autoPlay]);

  return (
    <div className="w-full">
      <div className="bg-black rounded-lg overflow-hidden">
        <div ref={playerRef} className="asciinema-player-container" />
      </div>
      <div className="mt-4 flex justify-center space-x-4">
        <button
          onClick={() => {
            const player = (playerRef.current as any)?._asciinemaPlayer;
            if (player) player.play();
          }}
          className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
        >
          播放
        </button>
        <button
          onClick={() => {
            const player = (playerRef.current as any)?._asciinemaPlayer;
            if (player) player.pause();
          }}
          className="px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600"
        >
          暂停
        </button>
        <button
          onClick={() => {
            const player = (playerRef.current as any)?._asciinemaPlayer;
            if (player) player.seek(0);
          }}
          className="px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600"
        >
          重播
        </button>
        <button
          onClick={() => {
            const player = (playerRef.current as any)?._asciinemaPlayer;
            if (player) {
              const speed = player.getSpeed();
              player.setSpeed(speed === 1 ? 2 : 1);
            }
          }}
          className="px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600"
        >
          切换速度
        </button>
      </div>
    </div>
  );
};
