// Code generated by spec-kit:implement; DO NOT EDIT.
// This file was generated at 2025-10-29 22:15:00
// Source: .claude/specs/010-k8s-pod-009/tasks.md (task: T031)

import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { formatDistanceToNow } from 'date-fns';
import { zhCN } from 'date-fns/locale';

interface K8sRecording {
  id: string;
  recording_type: 'k8s_node' | 'k8s_pod';
  title: string;
  status: string;
  start_time: string;
  end_time?: string;
  duration_seconds: number;
  user_id: string;
  file_path: string;
  type_metadata: {
    cluster_id: string;
    node_name?: string;
    namespace?: string;
    pod_name?: string;
    container_name?: string;
  };
}

interface Pagination {
  page: number;
  page_size: number;
  total: number;
  total_page: number;
}

export const K8sRecordingList: React.FC = () => {
  const [filters, setFilters] = useState({
    cluster_id: '',
    node_name: '',
    namespace: '',
    pod_name: '',
    container: '',
  });
  const [pagination, setPagination] = useState({
    page: 1,
    page_size: 20,
  });

  const { data, isLoading, error } = useQuery({
    queryKey: ['k8s-recordings', filters, pagination],
    queryFn: async () => {
      const params = new URLSearchParams();
      Object.entries(filters).forEach(([key, value]) => {
        if (value) params.append(key, value);
      });
      params.append('page', pagination.page.toString());
      params.append('page_size', pagination.page_size.toString());

      const response = await fetch(`/api/v1/recordings/k8s?${params}`);
      if (!response.ok) {
        throw new Error('Failed to fetch recordings');
      }
      return response.json();
    },
  });

  const handleFilterChange = (key: string, value: string) => {
    setFilters(prev => ({ ...prev, [key]: value }));
  };

  const handlePageChange = (newPage: number) => {
    setPagination(prev => ({ ...prev, page: newPage }));
  };

  if (isLoading) {
    return <div className="p-4">加载中...</div>;
  }

  if (error) {
    return <div className="p-4 text-red-500">加载失败</div>;
  }

  const recordings: K8sRecording[] = data?.data || [];
  const paginationData: Pagination = data?.pagination;

  return (
    <div className="p-6">
      <h2 className="text-2xl font-bold mb-6">K8s 终端录制</h2>

      {/* 筛选器 */}
      <div className="bg-white p-4 rounded-lg shadow mb-6">
        <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-4">
          <input
            type="text"
            placeholder="集群 ID"
            className="px-3 py-2 border rounded"
            value={filters.cluster_id}
            onChange={(e) => handleFilterChange('cluster_id', e.target.value)}
          />
          <input
            type="text"
            placeholder="节点名称"
            className="px-3 py-2 border rounded"
            value={filters.node_name}
            onChange={(e) => handleFilterChange('node_name', e.target.value)}
          />
          <input
            type="text"
            placeholder="命名空间"
            className="px-3 py-2 border rounded"
            value={filters.namespace}
            onChange={(e) => handleFilterChange('namespace', e.target.value)}
          />
          <input
            type="text"
            placeholder="Pod 名称"
            className="px-3 py-2 border rounded"
            value={filters.pod_name}
            onChange={(e) => handleFilterChange('pod_name', e.target.value)}
          />
          <input
            type="text"
            placeholder="容器名称"
            className="px-3 py-2 border rounded"
            value={filters.container}
            onChange={(e) => handleFilterChange('container', e.target.value)}
          />
        </div>
      </div>

      {/* 录制列表 */}
      <div className="bg-white rounded-lg shadow overflow-hidden">
        <table className="min-w-full">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">类型</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">标题</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">状态</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">持续时间</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">开始时间</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">操作</th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {recordings.map((recording) => (
              <tr key={recording.id}>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span className={`px-2 py-1 text-xs font-semibold rounded ${
                    recording.recording_type === 'k8s_node'
                      ? 'bg-blue-100 text-blue-800'
                      : 'bg-green-100 text-green-800'
                  }`}>
                    {recording.recording_type === 'k8s_node' ? '节点终端' : 'Pod 终端'}
                  </span>
                </td>
                <td className="px-6 py-4">
                  <div className="text-sm font-medium text-gray-900">{recording.title}</div>
                  <div className="text-sm text-gray-500">
                    {recording.type_metadata.cluster_id}
                    {recording.type_metadata.node_name && ` / ${recording.type_metadata.node_name}`}
                    {recording.type_metadata.namespace && ` / ${recording.type_metadata.namespace}`}
                    {recording.type_metadata.pod_name && ` / ${recording.type_metadata.pod_name}`}
                  </div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <span className={`px-2 py-1 text-xs font-semibold rounded ${
                    recording.status === 'active'
                      ? 'bg-yellow-100 text-yellow-800'
                      : recording.status === 'stopped'
                      ? 'bg-gray-100 text-gray-800'
                      : 'bg-red-100 text-red-800'
                  }`}>
                    {recording.status}
                  </span>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  {recording.duration_seconds > 0
                    ? `${Math.floor(recording.duration_seconds / 60)}分${recording.duration_seconds % 60}秒`
                    : '-'
                  }
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  {formatDistanceToNow(new Date(recording.start_time), {
                    addSuffix: true,
                    locale: zhCN
                  })}
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                  <button
                    onClick={() => window.open(`/api/v1/recordings/${recording.id}/play`, '_blank')}
                    className="text-blue-600 hover:text-blue-900 mr-4"
                  >
                    播放
                  </button>
                  <button
                    onClick={() => window.location.href = `/recordings/${recording.id}`}
                    className="text-green-600 hover:text-green-900"
                  >
                    详情
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* 分页 */}
        {paginationData && (
          <div className="bg-white px-4 py-3 border-t border-gray-200 sm:px-6">
            <div className="flex items-center justify-between">
              <div className="text-sm text-gray-700">
                显示第 {(paginationData.page - 1) * paginationData.page_size + 1} 到{' '}
                {Math.min(paginationData.page * paginationData.page_size, paginationData.total)} 条，
                共 {paginationData.total} 条
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => handlePageChange(paginationData.page - 1)}
                  disabled={paginationData.page === 1}
                  className="px-3 py-1 border rounded disabled:opacity-50"
                >
                  上一页
                </button>
                <span className="px-3 py-1">
                  {paginationData.page} / {paginationData.total_page}
                </span>
                <button
                  onClick={() => handlePageChange(paginationData.page + 1)}
                  disabled={paginationData.page === paginationData.total_page}
                  className="px-3 py-1 border rounded disabled:opacity-50"
                >
                  下一页
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
