name: Dev Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/release.yaml'

env:
  IMAGE_NAME: tiga
  GO_VERSION: "1.24.3"
  NODE_VERSION: "24"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ysicing' }}
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Generate timestamp tag
        id: timestamp
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "Building dev image with timestamp: $TIMESTAMP"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker hub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          cache: true

      - name: Build and push dev image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:dev
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:dev-${{ steps.timestamp.outputs.timestamp }}
            ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:dev
            ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:dev-${{ steps.timestamp.outputs.timestamp }}
          labels: |
            runnumber=${{ github.run_id }}
            branch=${{ github.ref_name }}
            commit=${{ github.sha }}
